version: 0.2

phases:
   pre_build:
     commands:
       - npm install
   build:
     commands:
       - npm run build

artifacts:
   files:
    - scripts/*
   discard-paths: no
   base-directory : build

